DROP TABLE Receiver;
DROP TABLE Messages;
DROP TABLE Education;
DROP TABLE Tags;
ALTER TABLE Photo
	DROP COLUMN Albumid ;
DROP TABLE Album;
DROP TABLE Photo;
DROP TABLE Participants;
DROP TABLE Event;
DROP TABLE Address;
DROP TABLE Location;
DROP TABLE Users;