
-- Check for USER_INFORMATION-----
SELECT count(*) FROM(
SELECT * FROM keykholt.PUBLIC_USER_INFORMATION
MINUS
SELECT * FROM VIEW_USER_INFORMATION
);



-- Check for PHOTO_INFORMATION-----
SELECT count(*) FROM(
SELECT * FROM keykholt.PUBLIC_PHOTO_INFORMATION
MINUS
SELECT * FROM VIEW_PHOTO_INFORMATION
);





-- Check for TAG_INFORMATION-----
SELECT count(*) FROM(
SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION
MINUS
SELECT * FROM VIEW_TAG_INFORMATION
);



-- Check for EVENT_INFORMATION-----
SELECT count(*) FROM(
SELECT * FROM keykholt.PUBLIC_EVENT_INFORMATION
MINUS
SELECT * FROM VIEW_EVENT_INFORMATION
);







