
SELECT count(*) FROM(
SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION
MINUS
SELECT * FROM VIEW_TAG_INFORMATION
);


-- 
--PUBLIC_ARE_FRIENDS
-- PUBLIC_USER_INFORMATION 
-- PUBLIC_ARE_FRIENDS 
-- PUBLIC_PHOTO_INFORMATION 
-- PUBLIC_TAG_INFORMATION 
-- PUBLIC_EVENT_INFORMATION

 -- VIEW_USER_INFORMATION
 -- VIEW_ARE_FRIENDS
 -- VIEW_PHOTO_INFORMATION
 -- VIEW_TAG_INFORMATION
 -- VIEW_EVENT_INFORMATION


-- SELECT count(*) FROM(
-- SELECT * FROM VIEW_TAG_INFORMATION
-- MINUS
-- SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION 
-- );

-- SELECT count(*) FROM(
-- SELECT * FROM VIEW_TAG_INFORMATION 
-- MINUS
-- SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION
-- );










